# cspell:ignore fileglob

- name: Configure Host
  hosts: all

  pre_tasks:
    - name: Include Playbook Configuration
      ansible.builtin.include_vars: "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  roles:
    - role: geerlingguy.mac.homebrew
      tags: ["homebrew"]

  tasks:
    - name: Include Rust automation tasks
      ansible.builtin.import_tasks: tasks/rust.yml
      tags: ['rust']

    - name: Include macOS defaults tasks
      ansible.builtin.import_tasks: tasks/macos.yml
      tags: ["macos"]
