# cspell:ignore fileglob

- name: Configure Host
  hosts: all

  pre_tasks:
    - name: Include Playbook Configuration
      ansible.builtin.include_vars: "{{ playbook_dir }}/config.yml"
      tags: ["always"]

    - name: Check if Homebrew is installed
      ansible.builtin.command: which brew
      register: homebrew_check
      changed_when: false
      failed_when: false
      tags: ["homebrew"]

    - name: Update Homebrew if already installed
      ansible.builtin.command: "{{ homebrew_check.stdout | trim }} update"
      when:
        - homebrew_check.rc == 0
        - (homebrew_check.stdout | trim | length) > 0
      register: homebrew_update
      changed_when: "'Already up-to-date' not in (homebrew_update.stdout | default(''))"
      tags: ["homebrew"]

  roles:
    - role: geerlingguy.mac.homebrew
      tags: ["homebrew"]

  tasks:
    - name: Include Rust automation tasks
      ansible.builtin.import_tasks: tasks/rust.yml
      tags: ['rust']
